### ISSUE TITLE
Noticed you were using mjpg-streamer... 

### ISSUE THREAD

**Issue by virtuald** [Team254/FRC-2017-Public#3]
As per https://github.com/robotpy/roborio-packages/issues/14 we're removing it in 2018. It's not a lot of work to keep it, so if that's something you care about then please comment on that issue.

**Comment by RaphaelMetz** [comment]
Our team uses it too; it would be a loss, but I'm sure we could use something else

**Comment by changsolomon8** [comment]
Thank you for the heads up.  We used the robotpy repository to easily install mjpg-streamer; furthermore, we launched mjpg-streamers as separate process to improve isolation between video feed and robot code.
We could have manually installed it as well (it seems like we will need to do this in the future)
